server:
  port: 9526

spring:
  datasource:
    name: statistic
    url: jdbc:mysql://192.168.0.250:3306/icb_statistics_db?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: icb@888
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat, wall
      initial-size: 10
      min-idle: 8
      max-active: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js, *.gif, *.jpg, *.png, *.css, *.ico, /druid/*"
        session-stat-enable: true
        session-stat-max-count: 100000
        profile-enable: true
        principal-session-name: spear
        principal-cookie-name: spear
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny:
      aop-patterns: com.shay.spear.service.*
      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            none-base-statement-allow: false
            update-where-none-check: true
            select-into-outfile-allow: false
            merge-allow: true
          log-violation: true
          throw-exception: true
  data:
    mongodb:
      uri: mongodb://root:icb%40888@192.168.0.234:13033/admin

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shay.spear.domain.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql